kind: ConfigMap
apiVersion: v1
metadata:
  name: deployment-cm
data:
  modules.json: |
   [
    {
      "Id": "VirtoCommerce.Assets",
      "Repository": "VirtoCommerce/vc-module-assets",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Assets_3.200.0-pr-4.zip"
    },
    {
      "Id": "VirtoCommerce.FileSystemAssets",
      "Repository": "VirtoCommerce/vc-module-filesystem-assets",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.FileSystemAssets_3.200.0-pr-3.zip"
    },
    {
      "Id": "VirtoCommerce.AzureBlobAssets",
      "Repository": "VirtoCommerce/vc-module-azureblob-assets",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.AzureBlobAssets_3.200.0-pr-3.zip"
    },
    {
      "Id": "VirtoCommerce.BulkActionsModule",
      "Repository": "VirtoCommerce/vc-module-bulk-actions",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.BulkActionsModule_3.200.0-pr-18.zip"
    },
    {
      "Id": "VirtoCommerce.Core",
      "Repository": "VirtoCommerce/vc-module-core",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Core_3.200.0-pr-199.zip"
    },
    {
      "Id": "VirtoCommerce.Cart",
      "Repository": "VirtoCommerce/vc-module-cart",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Cart_3.200.0-pr-96.zip"
    },
    {
      "Id": "VirtoCommerce.Catalog",
      "Repository": "VirtoCommerce/vc-module-catalog",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Catalog_3.202.0-pr-581.zip"
    },
    {
      "Id": "VirtoCommerce.Content",
      "Repository": "VirtoCommerce/vc-module-content",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Content_3.200.0-pr-97.zip"
    },
    {
      "Id": "VirtoCommerce.Customer",
      "Repository": "VirtoCommerce/vc-module-customer",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Customer_3.200.0-pr-162.zip"
    },
    {
      "Id": "VirtoCommerce.ElasticSearch",
      "Repository": "VirtoCommerce/vc-module-elastic-search",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ElasticSearch_3.200.0-pr-31.zip"
    },
    {
      "Id": "VirtoCommerce.Export",
      "Repository": "VirtoCommerce/vc-module-export",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Export_3.200.0-pr-63.zip"
    },
    {
      "Id": "VirtoCommerce.ImageTools",
      "Repository": "VirtoCommerce/vc-module-image-tools",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.ImageTools_3.200.0-pr-81.zip"
    },
    {
      "Id": "VirtoCommerce.Inventory",
      "Repository": "VirtoCommerce/vc-module-inventory",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Inventory_3.200.0-pr-101.zip"
    },
    {
      "Id": "VirtoCommerce.Marketing",
      "Repository": "VirtoCommerce/vc-module-marketing",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Marketing_3.200.0-pr-168.zip"
    },
    {
      "Id": "VirtoCommerce.Notifications",
      "Repository": "VirtoCommerce/vc-module-notification",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Notifications_3.200.0-pr-89.zip"
    },
    {
      "Id": "VirtoCommerce.Orders",
      "Repository": "VirtoCommerce/vc-module-order",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Orders_3.201.0-pr-281.zip"
    },
    {
      "Id": "VirtoCommerce.Payment",
      "Repository": "VirtoCommerce/vc-module-payment",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Payment_3.200.0-pr-31.zip"
    },
    {
      "Id": "VirtoCommerce.Pricing",
      "Repository": "VirtoCommerce/vc-module-pricing",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-pricing/releases/download/3.201.0/VirtoCommerce.Pricing_3.201.0.zip"
    },
    {
      "Id": "VirtoCommerce.Search",
      "Repository": "VirtoCommerce/vc-module-search",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Search_3.200.0-pr-53.zip"
    },
    {
      "Id": "VirtoCommerce.Shipping",
      "Repository": "VirtoCommerce/vc-module-shipping",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Shipping_3.200.0-pr-26.zip"
    },
    {
      "Id": "VirtoCommerce.Sitemaps",
      "Repository": "VirtoCommerce/vc-module-sitemaps",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Sitemaps_3.200.0-pr-40.zip"
    },
    {
      "Id": "VirtoCommerce.Store",
      "Repository": "VirtoCommerce/vc-module-store",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-store/releases/download/3.201.0/VirtoCommerce.Store_3.201.0.zip"
    },
    {
      "Id": "VirtoCommerce.Tax",
      "Repository": "VirtoCommerce/vc-module-tax",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Tax_3.200.0-pr-26.zip"
    },
    {
      "Id": "VirtoCommerce.CatalogCsvImportModule",
      "Repository": "VirtoCommerce/vc-module-catalog-csv-import",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.CatalogCsvImportModule_3.200.0-pr-89.zip"
    },
    {
      "Id": "VirtoCommerce.CustomerReviews",
      "Repository": "VirtoCommerce/vc-module-customer-review",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-customer-review/releases/download/3.200.0/VirtoCommerce.CustomerReviews_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.WebHooks",
      "Repository": "VirtoCommerce/vc-module-webhooks",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.WebHooks_3.200.0-pr-51.zip"
    },
    {
      "Id": "VirtoCommerce.ExperienceApi",
      "Repository": "VirtoCommerce/vc-module-experience-api",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-experience-api/releases/download/3.204.0/VirtoCommerce.ExperienceApi_3.204.0.zip"
    },
    {
      "Id": "VirtoCommerce.ProfileExperienceApiModule",
      "Repository": "VirtoCommerce/vc-module-profile-experience-api",
      "PackageUrl": "https://github.com/VirtoCommerce/vc-module-profile-experience-api/releases/download/3.200.0/VirtoCommerce.ProfileExperienceApiModule_3.200.0.zip"
    },
    {
      "Id": "VirtoCommerce.MarketplaceVendor",
      "Repository": "VirtoCommerce/vc-module-marketplace-vendor",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.MarketplaceVendor_3.200.0-alpha.137.zip"
    },
    {
      "Id": "VirtoCommerce.MarketplaceOperator",
      "Repository": "VirtoCommerce/vc-module-marketplace-operator",
      "PackageUrl": "https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.MarketplaceOperator_3.200.0-alpha.55.zip"
    }
   ]
