apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../common-base/platform
  - ../../common-base/storefront
    - ../../common-base/demo-manager


patchesStrategicMerge:
  - platform-cm.yaml
  - platform-deploy.yaml
  - platform-secrets.yaml
  - storefront-cm.yaml
  - storefront-deploy.yaml
  - themes-cm.yaml
  - deployment-cm.yaml

images:
- name: ghcr.io/virtocommerce/platform
  newName: ghcr.io/virtocommerce/platform
  newTag: 3.88.0-alpha.12150-dev-3c8be629
- name: ghcr.io/virtocommerce/platform-demo-manager
  newName: ghcr.io/virtocommerce/platform-demo-manager
  newTag: 0.0.99
- name: ghcr.io/virtocommerce/marketplace-storefront
  newName: ghcr.io/virtocommerce/marketplace-storefront
  newTag: 1.13.0-alpha.1040-dev-4942a30e
- name: ghcr.io/virtocommerce/demo-xapi-app
  newName: ghcr.io/virtocommerce/demo-xapi-app
  newTag: 1.0.0-alpha.16-vds-2423