kind: ConfigMap
apiVersion: v1
metadata:
  name: platform-cm
  annotations:
    reloader.stakater.com/match: true
data:
  ASPNETCORE_ENVIRONMENT: 'Development'
  APPINSIGHTS_INSTRUMENTATIONKEY: 'c6aa0ecf-ab70-4c46-a1a2-426a70d62e71'
  Marketplace__MasterCatalogId: '5aa50aaea01544529a6b6d576a668439'
  Marketplace__StoreId: 'B2B-store'
  Marketplace__VendorPortalUrl: 'https://vendor-portal.$(VC_NAMESPACE).govirto.com/'
  Search__ElasticSearch__Server: https://elasticsearch-dev.govirto.com
  Search__OrderFullTextSearchEnabled: 'true'
  Notifications__DefaultSender: 'azure_25da07ed75daacae20578a7a7dc58541@azure.com'
  Notifications__Gateway: 'SendGrid'
  Notifications__SmsDefaultSender: '+17012510519'
  Notifications__Smtp__EnableSsl: 'False'
  Notifications__Smtp__Host: 'smtp.sendgrid.net'
  Notifications__Smtp__Login: 'apikey'
  Notifications__Smtp__Port: '587'
  Marketplace__d365__BaseUrl: 'https://virtmpd3657c7fdb808917f525aos.cloud.retail.dynamics.com'
  Marketplace__d365__Tenant: '16d0ce93-4497-4fa4-89dd-bc2c74bdf65e'
  Marketplace__d365__ClientId: '507da3c8-bf1e-42be-b590-f0759617ab84'
  Marketplace__d365__ClientSecret: 'a347Q~ModvHSKaplNthqLLzAHxP-x0Z3Krv6h'
