kind: ConfigMap
apiVersion: v1
metadata:
  name: platform-cm
  annotations:
    reloader.stakater.com/match: true
data:
  ASPNETCORE_ENVIRONMENT: 'Development'
  Marketplace__MasterCatalogId: '5aa50aaea01544529a6b6d576a668439'
  Marketplace__StoreId: 'B2B-store'
  Marketplace__VendorPortalUrl: 'https://vendor-portal.$(VC_NAMESPACE).govirto.com/'
  Notifications__DefaultSender: 'azure_25da07ed75daacae20578a7a7dc58541@azure.com'
  Notifications__Gateway: 'SendGrid'