apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
spec:
  revisionHistoryLimit: 1
  replicas: 1
  template:
    metadata:
      annotations:
        configmap.reloader.stakater.com/reload: "vcmarketplace-platform-cm, vcmarketplace-deployment-cm, vcmarketplace-platform-secret-configmap"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "myapp"
        vault.hashicorp.com/agent-configmap: "vcmarketplace-platform-secret-configmap"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-requests-cpu: "25m"
        vault.hashicorp.com/agent-limits-cpu: "50m"
    spec:
      initContainers:
        - name: init-sqldatabase
          env:
            - name: VC_SAMPLE_DATA_DB
              value: vcmarketplace-platform_source
      containers:
        - name: vc-platform-web
          command:
            - "/bin/bash"
            - "-c"
          args: 
            - "source /vault/secrets/config_base && source /vault/secrets/config_custom && dotnet VirtoCommerce.Platform.Web.dll"
          volumeMounts:
            - mountPath: "/opt/virtocommerce/platform/wwwroot/cms-content"
              name: cms-content-data
      volumes:
        - name: cms-content-data
          persistentVolumeClaim:
            claimName: cms-content-volume