
kind: ConfigMap
apiVersion: v1
metadata:
  name: storefront-cm
data:
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: 'true'
  ASPNETCORE_ENVIRONMENT: 'Development'
  CookieAuthenticationOptions__ExpireTimeSpan: '12:00:00'
  SnapshotCollectorConfiguration__IsEnabled: 'false'
  VirtoCommerce__AppSettings__GoogleAnalytics__DomainName: '$(VC_STOREFRONT_SERVICE).$(VC_NAMESPACE).govirto.com'
  VirtoCommerce__SendAccountConfirmation: 'true'
  VirtoCommerce__DefaultStore: B2B-store