kind: ConfigMap
apiVersion: v1
metadata:
  name: storefront-cm
  annotations:
    reloader.stakater.com/match: "true"
data:
  VirtoCommerce__Endpoint__Password: 'store'
  VirtoCommerce__Endpoint__UserName: 'admin'
  VirtoCommerce__Endpoint__Url: 'https://$(VC_PLATFORM_SERVICE).$(VC_NAMESPACE).govirto.com'