- name: vcmp-main
  gitops: true
  servicePlan: S2
  platform:
    imageRepository: virtopaasregistrymain.azurecr.io/vcmp/platform
    config:
      ASPNETCORE_ENVIRONMENT: 'Development'
      APPINSIGHTS_INSTRUMENTATIONKEY: 'c6aa0ecf-ab70-4c46-a1a2-426a70d62e71'
      Marketplace__MasterCatalogId: '5aa50aaea01544529a6b6d576a668439'
      Marketplace__StoreId: 'B2B-store'
      Marketplace__VendorPortalUrl: https://vcmp-dev-demo-manager.paas.govirto.com/
      Search__ElasticSearch__Server: https://elasticsearch-demo.govirto.com
      Search__ElasticSearch__Key: Bf328fvg7vVJdef23
      Search__OrderFullTextSearchEnabled: 'true'
      Notifications__DefaultSender: 'azure_25da07ed75daacae20578a7a7dc58541@azure.com'
      Notifications__Gateway: 'SendGrid'
      Notifications__SmsDefaultSender: '+17012510519'
      Notifications__Smtp__EnableSsl: 'False'
      Notifications__Smtp__Host: 'smtp.sendgrid.net'
      Notifications__Smtp__Login: 'apikey'
      Notifications__Smtp__Port: '587'
      Marketplace__d365__BaseUrl: 'https://virtmpd3657c7fdb808917f525aos.cloud.retail.dynamics.com'
      Marketplace__d365__Tenant: '16d0ce93-4497-4fa4-89dd-bc2c74bdf65e'
      VirtoCommerce__SampleDataUrl: https://vc3prerelease.blob.core.windows.net/packages/clothing-and-electronics_3_0_1.zip
      VirtoCommerce__LocalUploadFolderPath: /opt/virtocommerce/platform/wwwroot/cms-content
    secretConfig:
      Notifications__SendGrid__ApiKey: sendkey
      Marketplace__d365__ClientSecret: d365clientsecret
  storefront:
    enabled: true
    imageRepository: virtopaasregistrymain.azurecr.io/vcmp/storefront
    config:
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: 'true'
      ASPNETCORE_ENVIRONMENT: 'Development'
      CookieAuthenticationOptions__ExpireTimeSpan: '12:00:00'
      SnapshotCollectorConfiguration__IsEnabled: 'false'
      VirtoCommerce__AppSettings__GoogleAnalytics__DomainName: https://vcmp-dev-store.paas.govirto.com/
      VirtoCommerce__SendAccountConfirmation: 'true'

      VirtoCommerce__Endpoint__Password: store
      VirtoCommerce__DefaultStore: B2B-store

    secretConfig: {}
    themes:
      B2B-store: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.9.0-pr-289-ef63-ef632054.zip
  ingress: {}
  customApps:
    app1:
      enabled: true
      type: standalone
      probePath: /
      name: demo-manager
      imageRepository: virtopaasregistrymain.azurecr.io/vcmp/vendor-portal
      imageTag: 1.0.32
      ingressPath: /(.*)
      platformPath:
      - /(api)(.*)
      - /(connect\/token)(.*)
      - /(pushNotificationHub)(.*)
      - /(Modules)(.*)
      storefrontPath: []
      servicePath: []
    app2:
      enabled: false
      platformPath: []
      storefrontPath: []
      servicePath: []
  protectedParameters:
    - platform.image.tag
    - storefront.image.tag
    - custom.app1.image.tag
