- name: vcmp-dev
  gitops: true
  production: false
  servicePlan: F1
  platform:
    imageRepository: virtopaasregistrymain.azurecr.io/vcmp/platform
    sqlReplica: false
    config:
      ASPNETCORE_ENVIRONMENT: Development
      APPINSIGHTS_INSTRUMENTATIONKEY: 8c4a3d98-a113-4779-9cf7-33a0412a9102
      AzureAd__ApplicationId: 86d04c35-143d-4d3c-aea2-8608e2186282
      AzureAd__Enabled: true
      AzureAd__Priority: 1
      AzureAd__TenantId: common
      AzureAd__ValidateIssuer: MultitenantAzureAD
      FrontendSecurity__OrganizationMaintainerRole: org-maintainer
      Marketplace__d365__BaseUrl: https://virtmpd3657c7fdb808917f525aos.cloud.retail.dynamics.com
      Marketplace__d365__Tenant: 16d0ce93-4497-4fa4-89dd-bc2c74bdf65e
      Marketplace__MasterCatalogId: 5aa50aaea01544529a6b6d576a668439
      Marketplace__StoreId: B2B-store
      Marketplace__VendorPortalUrl: https://vcmp-dev.paas.govirto.com/apps/vendor-portal/#/
      Notifications__DefaultSender: azure_25da07ed75daacae20578a7a7dc58541@azure.com
      Notifications__Gateway: SendGrid
      Notifications__SmsDefaultSender: +17012510519
      Notifications__Smtp__EnableSsl: False
      Notifications__Smtp__Host: smtp.sendgrid.net
      Notifications__Smtp__Login: apikey
      Notifications__Smtp__Port: 587
      PasswordLogin__Priority: 0
      Search__ElasticSearch__Server: https://elasticsearch-vc03.govirto.com
      Search__ElasticSearch__EnableCompatibilityMode: true
      Search__OrderFullTextSearchEnabled: true
      VirtoCommerce__SampleDataUrl: https://vc3prerelease.blob.core.windows.net/packages/clothing-and-electronics_3_0_2.zip
      VirtoCommerce__LocalUploadFolderPath: /opt/virtocommerce/platform/wwwroot/cms-content
    secretConfig:
      Notifications__SendGrid__ApiKey: sendkey
      Marketplace__d365__ClientSecret: d365clientsecret
  storefront:
    enabled: true
    imageRepository: virtopaasregistrymain.azurecr.io/vcmp/storefront
    servicePlan: F1
    config:
      APPINSIGHTS_INSTRUMENTATIONKEY: 1d9f37fe-9616-428a-856c-12ed99a79166
      ASPNETCORE_FORWARDEDHEADERS_ENABLED: true
      ASPNETCORE_ENVIRONMENT: Development
      CookieAuthenticationOptions__ExpireTimeSpan: 12:00:00
      SnapshotCollectorConfiguration__IsEnabled: false
      VirtoCommerce__AppSettings__GoogleAnalytics__DomainName: https://vcmp-dev-storefront.paas.govirto.com/
      VirtoCommerce__SendAccountConfirmation: true
      VirtoCommerce__Endpoint__Password: Password1
      VirtoCommerce__DefaultStore: B2B-store
      SYSTEM: Reload
    themes:
      B2B-store: https://vc3prerelease.blob.core.windows.net/packages/vc-theme-b2b-vue-1.32.0-alpha.737.zip
  ingress: {}
  customApps:
    app1:
      enabled: false
    app2:
      enabled: false
  protectedParameters:
    - platform.image.tag
    - storefront.image.tag
  version: 3.208
