apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- platform-deploy.yaml
- deployment-cm.yaml
- platform-cm.yaml
- platform-secrets.yaml

resources:
- ../../common-base
images:
- name: docker.pkg.github.com/virtocommerce/vc-platform/platform
  newName: ghcr.io/virtocommerce/platform
  newTag: 3.83.0-alpha.12126-dev-4666aaa6