apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
spec:
  revisionHistoryLimit: 2
  replicas: 1
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "myapp"
        vault.hashicorp.com/agent-configmap: "marketplace-operator-platform-secret-configmap"
        configmap.reloader.stakater.com/reload: "marketplace-operator-platform-cm, marketplace-operator-deployment-cm, marketplace-operator-platform-secret-configmap"
        vault.hashicorp.com/agent-requests-cpu: "25m"
        vault.hashicorp.com/agent-limits-cpu: "50m" 
    spec:
      initContainers:
        - name: init-sqldatabase
          env:
          - name: VC_SAMPLE_DATA_DB
            value: marketplace-src  