kind: ConfigMap
apiVersion: v1
metadata:
  name: themes-cm
data:
  B2B_THEME_URL:  https://vc3prerelease.blob.core.windows.net/packages/vc-demo-theme-b2b-1.14.0-pr-234-3f15feff.zip
  B2B_THEME_LOCATION: /mnt/cms-content/Themes/B2B-store
  ASSETS_URL: https://vcbacpac.blob.core.windows.net/dac-packages/webstore_assets_4.zip
  ASSETS_LOCATION: /mnt/cms-content/assets
