apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marketplace-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: demo
    server: https://kubernetes.default.svc
  project: prod-tenant
  source:
    path: marketplace-app/overlays/demo
    repoURL: https://github.com/VirtoCommerce/vc-deploy-marketplace
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true