apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: qa
namePrefix: vcmarketplace-
commonLabels:
  instance: vcmarketplace
resources:
  - storage.yaml
  - ../../resources

configMapGenerator:
- name: db-config
  literals:
    - VC_DB_HOST=vc-dev-dbserver.database.windows.net
    - VC_DB=vc-dev-dbserver
    - VC_DB_POOL=vc-dev-elasticpool
    - VC_DB_USER=virto
- name: vault-config
  literals:
    - VAULT_API_URL=http://vault-dev.vault-dev.svc.cluster.local:8200

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: cms-content-qa
  target:
    version: v1
    kind: PersistentVolume

- patch: |-
    - op: add
      path: /spec/template/spec/nodeSelector
      value: 
        agentpool: agentpool
  target:
    group: apps
    version: v1
    kind: Deployment
- patch: |-
    - op: replace
      path: /spec/volumeName
      value: marketplace-cms-content-volume-qa
  target:
    version: v1
    kind: PersistentVolumeClaim

vars:
- name: VC_DB_HOST
  objref:
    kind: ConfigMap
    name: db-config
    apiVersion: v1
  fieldref:
    fieldpath: data.VC_DB_HOST
- name: VC_DB
  objref:
    kind: ConfigMap
    name: db-config
    apiVersion: v1
  fieldref:
    fieldpath: data.VC_DB
- name: VC_DB_POOL
  objref:
    kind: ConfigMap
    name: db-config
    apiVersion: v1
  fieldref:
    fieldpath: data.VC_DB_POOL
- name: VC_DB_USER
  objref:
    kind: ConfigMap
    name: db-config
    apiVersion: v1
  fieldref:
    fieldpath: data.VC_DB_USER
- name: VAULT_API_URL
  objref:
    kind: ConfigMap
    name: vault-config
    apiVersion: v1
  fieldref:
    fieldpath: data.VAULT_API_URL