apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
spec:
  revisionHistoryLimit: 1
  replicas: 1
  template:
    spec:
      containers:
        - name: vc-platform-web
          volumeMounts:
            - mountPath: "/opt/virtocommerce/platform/wwwroot/cms-content"
              name: cms-content-data
      volumes:
        - name: cms-content-data
          persistentVolumeClaim:
            claimName: cms-content-volume-qa