apiVersion: v1
kind: PersistentVolume
metadata:
  name: cms-content-qa
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 200Mi
  csi: 
    driver: blob.csi.azure.com
    readOnly: false
    fsType: ext4 
    volumeHandle: mc_aks-cluster-dev_aks-dev_westus#fusefdb1fe6c3d1c4b1d814#marketplace-operator-cms-content-qa
    volumeAttributes:
      containername: marketplace-operator-cms-content-qa
      skuName: Premium_LRS

  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: "blob-premium"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cms-content-volume-qa
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
  volumeName: cms-content-qa
  storageClassName: "blob-premium"