name: Cloud infra deployment

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/**'
    branches: 
      - 'vcmp-*'

jobs:
  gitops-publish-infra:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
  
    - name: Install vc-build
      run: |
        dotnet tool install --global VirtoCommerce.GlobalTool

    - name: Update app
      run: |
        vc-build UpdateCloudEnvironment -CloudToken ${{ secrets.VCMP_PLATFORM_TOKEN }} -ArgoConfigFile $ENV_FILE -CloudUrl https://portal.virtocommerce.cloud
      env:
        ENV_FILE: './infra/environments.yml'
        ARGO_SERVER: https://argo.virtocommerce.cloud
        TOKEN: ${{ secrets.VCMP_TOKEN }}
