name: marketplace gitops

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/**'
    branches: 
      - 'vcmp-*'

jobs:
  gitops:
    runs-on: ubuntu-20.04

    steps:
    - run: echo "Temporary disabled"
      # - uses: actions/checkout@v3
   
      # - name: Install vc-build
      #   run: |
      #     dotnet tool install --global VirtoCommerce.GlobalTool

      # - name: Update app
      #   run: |
      #     vc-build UpdateCloudEnvironment -CloudToken ${{ secrets.VCMP_PLATFORM_TOKEN }} -ArgoConfigFile $ENV_FILE -CloudUrl https://cloud.prod.govirto.com
      #   env:
      #     ENV_FILE: './infra/environments.yml'
      #     ARGO_SERVER: https://argocd.govirto.com
      #     TOKEN: ${{ secrets.VCMP_TOKEN }}
