name: marketplace gitops

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/**'
    branches: [ paas ]

jobs:
  gitops:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Install vc-build
      run: |
        dotnet tool install --global VirtoCommerce.GlobalTool --version 3.3.0
    
    - name: Update app
      run: |
        vc-build ArgoUpdateApplication -ArgoConfigFile $ENV_FILE -ArgoServer $ARGO_SERVER -ArgoToken $TOKEN
      env:
        ENV_FILE: './infra/environments.yml'
        ARGO_SERVER: https://argo.govirto.com
        TOKEN: ${{ secrets.VCMP_TOKEN }}