name: Cloud storefront deployment

on:
  workflow_dispatch:
  push:
    paths:
      - 'storefront/**'
    branches: 
      - 'vcmp-*'

jobs:
  gitops-publish-storefront:
    runs-on: ubuntu-20.04
    env:
      DOCKER_LOGIN: vcmp-token
      DOCKER_PASSWORD: ${{ secrets.VCMP_ACR_DOCKER_PASSWORD }}
      CONTAINER_REGISTRY: virtopaasregistrymain.azurecr.io
      IMAGE_REPOSITORY: virtopaasregistrymain.azurecr.io/vcmp/storefront
      ARGO_TOKEN: ${{ secrets.VCMP_TOKEN }}
      ARGO_APP_NAME: ${{ github.ref_name }}

    steps:
    - run: echo "Temporary disabled"
    - uses: actions/checkout@v3
    
    - name: Install vc-build
      run: |
        dotnet tool install --global VirtoCommerce.GlobalTool
    
    - name: Get storefront version
      id: platform-version
      run: |
        echo "STOREFRONT_TAG=$(cat ./storefront/image.json | jq -r '.Tag')" >> $GITHUB_ENV
        echo "STOREFRONT_REPO=$(cat ./storefront/image.json | jq -r '.Repository')" >> $GITHUB_ENV

    - name: Docker Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.CONTAINER_REGISTRY }}
        username: ${{ env.DOCKER_LOGIN }}
        password: ${{ env.DOCKER_PASSWORD }}

    - name: Publish platform image to the Virto Cloud
      run: |
        docker pull ${{ env.STOREFRONT_REPO }}:${{ env.STOREFRONT_TAG }}
        docker tag ${{ env.STOREFRONT_REPO }}:${{ env.STOREFRONT_TAG }} ${{ env.IMAGE_REPOSITORY }}:${{ env.STOREFRONT_TAG }}
        docker push ${{ env.IMAGE_REPOSITORY }}:${{ env.STOREFRONT_TAG }}

    - name: Update app
      run: |
        vc-build SetHelmParameter -ArgoServer https://argocd.govirto.com -ArgoAppName ${{ env.ARGO_APP_NAME }} -ArgoToken ${{ env.ARGO_TOKEN }} -HelmParameters storefront.image.tag=$TAG
      env:
        TAG: ${{ env.STOREFRONT_TAG }}
